info:
  component: nantes jug 2017 
  apis: 
   description: liste des api disponibles pour le nantes jug 2017


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
spring:
  application:
    name: zuul-server
 
server:
  port: 8051
  
logging:
  level:
    com.netflix: 'DEBUG'
    org.springframework.cloud: 'DEBUG'
  file: c:/Dev/logs/nantesjug/cuves.log
  
  
eureka:
  instance:
    hostname: localhost
    port: 8050
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8050/eureka/
    healthcheck:
      enabled: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    annuaire-personne:
      path: /rest/personnages/**
      serviceId: ANNUAIRE-PERSONNE
      stripPrefix: false
    annuaire-reacteur:
      path: /rest/reacteurs/**
      serviceId: ANNUAIRE-REACTEUR
      stripPrefix: false
    annuaire-cuve:
      path: /rest/cuves/**
      serviceId: ANNUAIRE-CUVES
      stripPrefix: false
      
instance:
  #Virtual host name by which the clients identifies this service
  virtualHostName: ${spring.application.name}
  
turbine:
  clusterNameExpression: "default"
  appConfig: ANNUAIRE-PERSONNE,ANNUAIRE-REACTEUR,ANNUAIRE-CUVES

hystrix:
  streamEnabled: true
              